name: color
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch==2.0.1
      - torchvision==0.15.2
      - pytorch-lightning==2.0.6
      - torchmetrics==0.11.4
      - hydra-core==1.0.7
      - omegaconf==2.0.6
      - wandb==0.15.8
      - git+https://github.com/openai/CLIP.git
      - transformers==4.42.4
      - scikit-learn==1.3.2
      - scipy==1.7.3
      - numpy==1.21.0
      - pandas==2.0.3
      - abstention
      - lion-pytorch
      - huggingface-hub>=0.24
      - matplotlib==3.7.5
      - seaborn==0.13.2
      - tqdm
      - Pillow
      - PyYAML
